### ISSUE TITLE
"dot" not found in path

### ISSUE THREAD

**Issue by ghost** [niveknosredneh/PFSG#1]
I tried you programm on a small directory, the directory i use to store my personnals github and github i cloned. I have all dependencies, and i tried this command :
``` ./pfsg.py /home/luc/github/ dot.png -w 1920 -h 1080 -l dot```
But i have the following error : 
```FileNotFoundError: [Errno 2] "dot" not found in path. FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'``` 
with a bunch of other things i can add if needed.

What's the problem ?

**Comment by kvnhndrsn** [comment]
I am not on arch but someone has said this may work:
`sudo pacman -S python-pygraphviz`

**Comment by ghost** [comment]
Now i have ```ModuleNotFoundError: No module named 'matplotlib'```

**Comment by kvnhndrsn** [comment]
I have only tested this on python3.  Maybe try python3-matplotlib or python3-pygraphviz.  I am sorry I do not have an arch install to test dependencies on.

**Comment by ghost** [comment]
Now i have that things : 
```/usr/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py:579: MatplotlibDeprecationWarning: The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.  if not cb.iterable(width):```

**Comment by kvnhndrsn** [comment]
please try the new testing version.  I have removed a couple python dependencies.
` wget https://raw.githubusercontent.com/niveknosredneh/PFSG/testing/pfsg.py `

**Comment by ghost** [comment]
Working, thanks a lot !
